name: Release Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    permissions:
        contents: read      # 读取仓库内容
        packages: write     # 上传和下载发布资产
        id-token: write     # 用于身份验证

    steps:
    - uses: actions/checkout@v3

    - name: 生成 GitHub App 临时令牌
      id: auth
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.BOT_APP_ID }}
        private-key: ${{ secrets.BOT_APP_SECRET }}
        owner: ${{ github.repository_owner }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        pyinstaller -w main.py
        
    - name: Copy data files
      run: |
        xcopy .\data .\dist\main\data /E /I
        
    - name: Compress build output
      run: |
        Compress-Archive -Path .\dist\main\* -DestinationPath .\dist\release.zip
        
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: .\dist\release.zip
        asset_name: release.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
        